name: Run Tests
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  flake8:
    name: Style Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - run: sudo apt-get update
      - run: sudo apt-get install -qy libxml2-dev libxslt-dev
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: pip install .
      - run: pip install flake8
      - run: flake8
  pytype:
    name: Type Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - run: sudo apt-get update
      - run: sudo apt-get install -qy libxml2-dev libxslt-dev
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: pip install .
      - run: pip install pytype
      - run: pytype cstug_to_dmlcz
